name: Docker Image Azure Container Registry CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push-to-acr:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Step 3: Build and tag the Docker image
    - name: Build and tag the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.ACR_URL }}/spinboard-go:${{ github.sha }}
        docker tag ${{ secrets.ACR_URL }}/spinboard-go:${{ github.sha }} ${{ secrets.ACR_URL }}/spinboard-go:latest

    # Step 4: Push both tags to ACR
    - name: Push Docker images to ACR
      run: |
        docker push ${{ secrets.ACR_URL }}/spinboard-go:${{ github.sha }}
        docker push ${{ secrets.ACR_URL }}/spinboard-go:latest
