name: Build and deploy container app to Azure Web App - spinboard

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://shabbiregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_747e3b4693a9431dbacf3559d00dc9a9 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_2d4e1dd68b08419098e523d69e68e438 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: shabbiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_747e3b4693a9431dbacf3559d00dc9a9 }}/spinboard-go:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spinboard'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_254c7137e116400386499e0c39d7fbf7 }}
          images: 'shabbiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_747e3b4693a9431dbacf3559d00dc9a9 }}/spinboard-go:${{ github.sha }}'
